[package]
name = "tari_node_components"
description = "Tari Base Layer Node Components"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
wasm = ["wasm-bindgen"]

[dependencies]
tari_common_types = { workspace = true }
tari_hashing = { workspace = true }
tari_transaction_components = { workspace = true }
tari_utilities = { workspace = true, features = ["borsh"] }

blake2 = "0.10"
borsh = { version = "1.5.7", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
digest = "0.10"
log = "0.4"
primitive-types = { version = "0.12", features = ["serde"] }
serde = { version = "1.0.106", features = ["derive"] }
thiserror = "1.0.26"
wasm-bindgen = { version = "0.2.100", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", features = ["serde", "wasmbind"] }

js-sys = { version = "0.3.55" }

[dev-dependencies]


[lib]
crate-type = ["cdylib", "rlib"]


[package.metadata.cargo-machete]
ignored = [
] # this is so we can run cargo machete without getting false positive about macro dependancies
