// Copyright 2019. The Tari Project
//
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
// following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
// disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
// following disclaimer in the documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
// products derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

use std::fmt;

use serde::{Deserialize, Serialize};
use tari_common_types::{
    tari_address::TariAddress,
    transaction::TxId,
    types::{CompressedCommitment, CompressedPublicKey, PrivateKey, Signature, UncompressedCommitment},
};
pub use tari_key_manager::key_manager_service::KeyId;
use tari_script::TariScript;

use crate::{
    covenants::Covenant,
    transactions::{
        legacy_transaction_protocol::{TransactionMetadata, TransactionProtocolError as TPE},
        tari_amount::*,
        transaction_components::{
            memo_field::MemoField,
            OutputFeatures,
            Transaction,
            TransactionKernelVersion,
            TransactionOutput,
            TransactionOutputVersion,
            WalletOutput,
        },
        transaction_key_manager::{TariKeyId, TransactionKeyManagerInterface},
    },
};

//----------------------------------------   Local Data types     ----------------------------------------------------//
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct LegacyOutputPair {
    pub output: WalletOutput,
    pub kernel_nonce: TariKeyId,
    pub sender_offset_key_id: Option<TariKeyId>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub(super) struct RecipientDetails {
    pub amount: MicroMinotari,
    pub recipient_output_features: OutputFeatures,
    pub recipient_script: TariScript,
    pub recipient_sender_offset_key_id: TariKeyId,
    pub recipient_covenant: Covenant,
    pub recipient_minimum_value_promise: MicroMinotari,
    pub recipient_ephemeral_public_key_nonce: TariKeyId,
    pub recipient_address: TariAddress,
}

/// This struct contains all the information that a transaction initiator (the sender) will manage throughout the
/// Transaction construction process.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub(super) struct RawTransactionInfo {
    /// The transaction ID is a u64 identifier for the transaction generated by the sender
    pub tx_id: TxId,
    /// Details for the construction of the recipient output. OutputFeatures etc.
    pub recipient_data: Option<RecipientDetails>,
    /// The TransactionOutput received from the recipient.
    pub recipient_output: Option<TransactionOutput>,
    /// The partial kernel excess received from the recipient.
    pub recipient_partial_kernel_excess: CompressedPublicKey,
    /// The partial kernel signature received from the recipient.
    pub recipient_partial_kernel_signature: Signature,
    /// The partial kernel offset received from the recipient.
    pub recipient_partial_kernel_offset: PrivateKey,
    /// The change output details. This may be None if no change is required.
    pub change_output: Option<LegacyOutputPair>,
    /// All transaction inputs inputs.
    pub inputs: Vec<LegacyOutputPair>,
    /// The recipient's outputs.
    pub outputs: Vec<LegacyOutputPair>,
    // cached data
    /// The total excess for this transaction. Excess is outputs + change_output - inputs. This is calculated when
    /// sender sends single round message to receiver
    pub total_sender_excess: CompressedPublicKey,
    /// The total public nonce for the transaction signature. This is calculated when sender sends single round message
    /// to receiver.
    pub total_sender_nonce: CompressedPublicKey,
    /// Details used to construct the transaction kernel.
    pub metadata: TransactionMetadata,
    /// A user payment ID for the sender/receiver
    pub payment_id: MemoField,
    /// The senders address
    pub sender_address: TariAddress,
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct SingleRoundSenderData {
    /// The transaction id generated by the sender for the recipient
    pub tx_id: TxId,
    /// The amount, in µT, being sent to the recipient
    pub amount: MicroMinotari,
    /// The offset public excess for this transaction
    pub public_excess: CompressedPublicKey,
    /// The sender's public nonce
    pub public_nonce: CompressedPublicKey,
    /// Metadata used to construct the transaction kernel
    pub metadata: TransactionMetadata,
    /// A user payment ID for the sender/receiver
    pub payment_id: MemoField,
    /// The output's features
    pub features: OutputFeatures,
    /// Script
    pub script: TariScript,
    /// Script offset public key
    pub sender_offset_public_key: CompressedPublicKey,
    /// The sender's ephemeral nonce
    pub ephemeral_public_nonce: CompressedPublicKey,
    /// Covenant
    pub covenant: Covenant,
    /// The minimum value of the commitment that is proven by the range proof
    pub minimum_value_promise: MicroMinotari,
    /// The version of this transaction output
    pub output_version: TransactionOutputVersion,
    /// The version of this transaction kernel
    pub kernel_version: TransactionKernelVersion,
    /// The senders address
    pub sender_address: TariAddress,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TransactionSenderMessage {
    None,
    Single(Box<SingleRoundSenderData>),
    Multiple,
}

impl TransactionSenderMessage {
    pub fn new_single_round_message(single_round_data: SingleRoundSenderData) -> Self {
        Self::Single(Box::new(single_round_data))
    }

    pub fn single(&self) -> Option<&SingleRoundSenderData> {
        match self {
            TransactionSenderMessage::Single(m) => Some(m),
            _ => None,
        }
    }
}

//----------------------------------------  Sender State Protocol ----------------------------------------------------//
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct SenderTransactionProtocol {
    state: SenderState,
}

impl SenderTransactionProtocol {
    /// Convenience method to check whether we're receiving recipient data
    pub fn is_collecting_single_signature(&self) -> bool {
        matches!(&self.state, SenderState::CollectingSingleSignature(_))
    }

    /// Convenience method to check whether we're ready to send a message to a single recipient
    pub fn is_single_round_message_ready(&self) -> bool {
        matches!(&self.state, SenderState::SingleRoundMessageReady(_))
    }

    /// Method to determine if we are in the SenderState::Finalizing state
    pub fn is_finalizing(&self) -> bool {
        matches!(&self.state, SenderState::Finalizing(_))
    }

    /// Method to determine if we are in the SenderState::FinalizedTransaction state
    pub fn is_finalized(&self) -> bool {
        matches!(&self.state, SenderState::FinalizedTransaction { .. })
    }

    /// Returns the finalized transaction if the protocol is in the Finalised state. Otherwise it returns an
    /// `InvalidStateError`.
    pub fn get_transaction(&self) -> Result<&Transaction, TPE> {
        match &self.state {
            SenderState::FinalizedTransaction {
                final_transaction: tx,
                change_output: _,
            } => Ok(tx),
            _ => Err(TPE::InvalidStateError),
        }
    }

    /// Returns the finalized transaction if the protocol is in the Finalised state and consumes the protocol object.
    /// Otherwise it returns an `InvalidStateError`. To keep the object and return a reference to the transaction, see
    /// [get_transaction].
    pub fn into_transaction(self) -> Result<Transaction, TPE> {
        match self.state {
            SenderState::FinalizedTransaction {
                final_transaction: tx,
                change_output: _,
            } => Ok(tx),
            _ => Err(TPE::InvalidStateError),
        }
    }

    /// Method to determine if the transaction protocol has failed
    pub fn is_failed(&self) -> bool {
        matches!(&self.state, SenderState::Failed(_))
    }

    /// Method to return the error behind a failure, if one has occurred
    pub fn failure_reason(&self) -> Option<TPE> {
        match &self.state {
            SenderState::Failed(e) => Some(e.clone()),
            _ => None,
        }
    }

    /// Method to check if the provided tx_id matches this transaction
    pub fn check_tx_id(&self, tx_id: TxId) -> bool {
        match &self.state {
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => info.tx_id == tx_id,
            _ => false,
        }
    }

    pub fn get_tx_id(&self) -> Result<TxId, TPE> {
        match &self.state {
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => Ok(info.tx_id),
            _ => Err(TPE::InvalidStateError),
        }
    }

    pub fn get_amount_to_recipient(&self) -> Result<MicroMinotari, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => Ok(info
                .recipient_data
                .as_ref()
                .map(|data| data.amount)
                .unwrap_or(MicroMinotari::zero())),
            SenderState::FinalizedTransaction { .. } => Err(TPE::InvalidStateError),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    /// This function will return the total value of outputs being sent to yourself in the transaction including the
    /// change
    pub fn get_amount_to_self(&self) -> Result<MicroMinotari, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => {
                let mut amount = info
                    .change_output
                    .as_ref()
                    .map(|output| output.output.value)
                    .unwrap_or(MicroMinotari::zero());
                for output in &info.outputs {
                    amount += output.output.value
                }
                Ok(amount)
            },
            SenderState::FinalizedTransaction { .. } => Err(TPE::InvalidStateError),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    /// This function will return the value of the change transaction
    pub fn get_change_amount(&self) -> Result<MicroMinotari, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => Ok(info
                .change_output
                .as_ref()
                .map(|output| output.output.value)
                .unwrap_or(MicroMinotari::zero())),
            SenderState::FinalizedTransaction {
                final_transaction: _,
                change_output: change,
            } => Ok(change
                .as_ref()
                .as_ref()
                .map(|o| o.output.value)
                .unwrap_or(MicroMinotari::zero())),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    /// Returns the change output for a non-finalized transaction. If the transaction is finalized, or failed, an error
    /// is returned.
    pub fn get_pre_finalized_change_output(&self) -> Result<Option<WalletOutput>, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => {
                Ok(info.change_output.as_ref().as_ref().map(|output| output.output.clone()))
            },
            SenderState::FinalizedTransaction { .. } => Err(TPE::InvalidStateError),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    /// Returns full change output for a non-finalized transaction. If the transaction is finalized, or failed, an error
    /// is returned.
    pub fn get_pre_finalized_full_change_output(&self) -> Result<Option<LegacyOutputPair>, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => Ok(info.change_output.clone()),
            SenderState::FinalizedTransaction { .. } => Err(TPE::InvalidStateError),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    /// Returns the change output for finalized transaction. If the transaction is not finalized, or failed, an error
    /// is returned.
    pub fn get_finalized_change_output(&self) -> Result<Option<WalletOutput>, TPE> {
        match &self.state {
            SenderState::Initializing(_) |
            SenderState::Finalizing(_) |
            SenderState::SingleRoundMessageReady(_) |
            SenderState::CollectingSingleSignature(_) |
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
            SenderState::FinalizedTransaction {
                final_transaction: _,
                change_output,
            } => Ok(change_output.as_ref().as_ref().map(|o| o.output.clone())),
        }
    }

    /// Returns the spent inputs for a non-finalized transaction. If the transaction is finalized, or failed, an error
    /// is returned.
    pub fn get_spent_inputs(&self) -> Result<Vec<LegacyOutputPair>, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => Ok(info.inputs.clone()),
            SenderState::FinalizedTransaction { .. } => Err(TPE::InvalidStateError),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    /// Returns the outputs for a non-finalized transaction. If the transaction is finalized, or failed, an error
    /// is returned.
    pub fn get_outputs(&self) -> Result<Vec<LegacyOutputPair>, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => Ok(info.outputs.clone()),
            SenderState::FinalizedTransaction { .. } => Err(TPE::InvalidStateError),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    /// This function will return the script offset private keys for a single recipient
    pub fn get_recipient_sender_offset_private_key(&self) -> Result<Option<TariKeyId>, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => Ok({
                info.recipient_data
                    .as_ref()
                    .map(|data| data.recipient_sender_offset_key_id.clone())
            }),
            SenderState::FinalizedTransaction { .. } => Err(TPE::InvalidStateError),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    pub fn change_recipient_sender_offset_private_key(&mut self, key_id: TariKeyId) -> Result<(), TPE> {
        match &mut self.state {
            SenderState::Initializing(ref mut info) |
            SenderState::Finalizing(ref mut info) |
            SenderState::SingleRoundMessageReady(ref mut info) |
            SenderState::CollectingSingleSignature(ref mut info) => {
                if let Some(ref mut v) = info.recipient_data {
                    v.recipient_sender_offset_key_id = key_id;
                }
            },
            SenderState::FinalizedTransaction { .. } | SenderState::Failed(_) => return Err(TPE::InvalidStateError),
        }

        Ok(())
    }

    /// This function will return the value of the fee of this transaction
    pub fn get_fee_amount(&self) -> Result<MicroMinotari, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => Ok(info.metadata.fee),
            SenderState::FinalizedTransaction {
                final_transaction: txn,
                change_output: _,
            } => Ok(txn.body.kernels().first().ok_or(TPE::InvalidStateError)?.fee),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    /// Create an empty SenderTransactionProtocol that can be used as a placeholder in data structures that do not
    /// require a well formed version
    pub fn new_placeholder() -> Self {
        SenderTransactionProtocol {
            state: SenderState::Failed(TPE::IncompleteStateError("This is a placeholder protocol".to_string())),
        }
    }

    pub async fn get_output_commitments<KM: TransactionKeyManagerInterface>(
        &self,
        km: &KM,
    ) -> Result<Vec<CompressedCommitment>, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => {
                let mut commitments = Vec::new();
                for output in &info.outputs {
                    commitments.push(output.output.to_transaction_output(km).await?.commitment);
                }
                if let Some(change) = info.change_output.as_ref() {
                    commitments.push(change.output.to_transaction_output(km).await?.commitment);
                }
                if let Some(recipient) = info.recipient_output.as_ref() {
                    commitments.push(recipient.commitment.clone());
                }
                Ok(commitments)
            },
            SenderState::FinalizedTransaction {
                final_transaction: txn,
                change_output: _,
            } => Ok(txn.body.outputs().iter().map(|o| o.commitment.clone()).collect()),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }

    pub async fn get_input_commitments<KM: TransactionKeyManagerInterface>(
        &self,
        km: &KM,
    ) -> Result<Vec<CompressedCommitment>, TPE> {
        match &self.state {
            SenderState::Initializing(info) |
            SenderState::Finalizing(info) |
            SenderState::SingleRoundMessageReady(info) |
            SenderState::CollectingSingleSignature(info) => {
                let mut commitments = Vec::new();
                for output in &info.inputs {
                    commitments.push(output.output.to_transaction_output(km).await?.commitment);
                }
                Ok(commitments)
            },
            SenderState::FinalizedTransaction {
                final_transaction: txn,
                change_output: _,
            } => Ok(txn
                .body
                .inputs()
                .iter()
                .map(|i| {
                    i.commitment()
                        .unwrap_or(&CompressedCommitment::from_commitment(UncompressedCommitment::default()))
                        .clone()
                })
                .collect()),
            SenderState::Failed(_) => Err(TPE::InvalidStateError),
        }
    }
    // #[cfg(test)]
    // pub(super) fn into_state(self) -> SenderState {
    //     self.state
    // }
}

impl From<SenderState> for SenderTransactionProtocol {
    fn from(state: SenderState) -> Self {
        Self { state }
    }
}

impl fmt::Display for SenderTransactionProtocol {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.state)
    }
}

//----------------------------------------      Sender State      ----------------------------------------------------//

/// This enum contains all the states of the Sender state machine
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub(super) enum SenderState {
    /// Transitional state that kicks of the relevant transaction protocol
    Initializing(Box<RawTransactionInfo>),
    /// The message for the recipient in a single-round scheme is ready
    SingleRoundMessageReady(Box<RawTransactionInfo>),
    /// Waiting for the signed transaction data in the single-round protocol
    CollectingSingleSignature(Box<RawTransactionInfo>),
    /// The final transaction state is being validated - it will automatically transition to Failed or Finalized from
    /// here
    Finalizing(Box<RawTransactionInfo>),
    /// The final transaction is ready to be broadcast
    FinalizedTransaction {
        final_transaction: Transaction,
        change_output: Box<Option<LegacyOutputPair>>,
    },
    /// An unrecoverable failure has occurred and the transaction must be abandoned
    Failed(TPE),
}

impl fmt::Display for SenderState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        #[allow(clippy::enum_glob_use)]
        use SenderState::*;
        match self {
            Initializing(info) => write!(
                f,
                "Initializing({} input(s), {} output(s))",
                info.inputs.len(),
                info.outputs.len()
            ),
            SingleRoundMessageReady(info) => write!(
                f,
                "SingleRoundMessageReady({} input(s), {} output(s))",
                info.inputs.len(),
                info.outputs.len()
            ),
            CollectingSingleSignature(info) => write!(
                f,
                "CollectingSingleSignature({} input(s), {} output(s))",
                info.inputs.len(),
                info.outputs.len()
            ),
            Finalizing(info) => write!(
                f,
                "Finalizing({} input(s), {} output(s))",
                info.inputs.len(),
                info.outputs.len()
            ),
            FinalizedTransaction {
                final_transaction: txn,
                change_output,
            } => write!(
                f,
                "FinalizedTransaction({} input(s), {} output(s)) with change output: {}",
                txn.body.inputs().len(),
                txn.body.outputs().len(),
                change_output.is_some(),
            ),
            Failed(err) => write!(f, "Failed({err:?})"),
        }
    }
}
