We are going to create unit tests for LMDB in the base_layer/core/src/chain_storage/lmdb_db/ directory.
 Steps:
 1. We need to create a test chain (genesis, 10 main-chain blocks, and a 10-block fork from block 5).
 2. We will create a reference LMDB file and a JSON file for the test chain data.
 3. We will write two unit tests:
    a. A write test: creates a new LMDB from the JSON data and bit-compares with the reference.
    b. A read test: loads the reference LMDB and verifies all data can be fetched correctly.

 However, note that the issue says: "Create a reproducible test chain ... and write two unit tests".

 Since we are in the Tari codebase, we should look for existing test utilities and follow the patterns.

 We are going to:
   - Create a new test file in `base_layer/core/src/chain_storage/lmdb_db/` (or in the tests directory?).
   - But note: the issue says the relevant code is in `base_layer/core/src/chain_storage/lmdb_db/`.

 However, unit tests for the LMDB database are likely to be in the same module or in a tests subdirectory.

 Let's assume we are to write the tests in `base_layer/core/src/chain_storage/lmdb_db/tests.rs` or similar.

 But note: the issue says "Create a reproducible test chain", meaning we have to generate the test data.

 Approach for generating the test chain:
   - We can use the existing test utilities in the Tari codebase for creating blocks (like in the blockchain tests).

 We note that the Tari codebase has a `test_helpers` module in the base_layer.

 However, to avoid external dependencies in the test, we can generate the chain using the same methods as in the existing tests.

 Since we are to create a reference LMDB file and a JSON file, we have two options:
   Option 1: Generate the test chain in the test setup and then write the reference LMDB and JSON to disk (in the test directory) and then use them in the tests.
   Option 2: Pre-generate the reference files and commit them to the repo.

 The issue says: "Create a reference LMDB file" and "All block data is saved in a JSON file for reproducibility".

 We are going to pre-generate the reference files and commit them? But note: the issue says "reproducible", meaning we can generate them in the test.

 However, generating the reference LMDB and JSON every time might be heavy and non-deterministic? We want the same reference every time.

 Let's decide: We will generate the test chain in the test setup (using a fixed seed) and then:
   - For the write test: we will create a temporary LMDB, write the chain, and then compare it to a reference LMDB that we have generated once and stored in the test resources.
   - For the read test: we will load the reference LMDB and verify.

 But note: the issue says "bit-compares it against a reference", meaning we need a reference LMDB file.

 How to handle:
   We can generate the reference LMDB and JSON in a setup script and then commit them to the test resources.

 However, the issue does not specify whether we should commit the reference files. Since it's a unit test, we can generate the reference in the test setup and then use it for the write test? But then the write test would be comparing to a reference that is generated in the same way? That doesn't test the LMDB writing because we are using the same code to generate the reference and to write.

 Alternatively, we can generate the chain data (blocks) independently (using a deterministic method) and then:
   - Write the chain to LMDB using the LMDB database (the code under test) and then compare the resulting LMDB file to a precomputed reference (which we generated by the same deterministic method but using a known good implementation?).

 But note: we are testing the LMDB implementation. We don't have another implementation to compare to.

 Therefore, we must rely on the fact that the LMDB implementation is correct if it produces the same output as a reference that we trust.

 How to get the reference? We can generate the chain data (the blocks) and then write them using a simple, trusted method (like writing to a file in a known format) and then use that to generate the reference LMDB by hand? That doesn't scale.

 Alternatively, we can use the existing Tari blockchain test infrastructure to generate the chain and then write the LMDB using the code under test, and then we consider that as the reference? But then we are testing nothing.

 We need a reference that is independent of the code under test.

 Since we are in the Tari project, we can use the existing block creation functions (which are tested elsewhere) to generate the chain data, and then we can write the LMDB using the code under test and then compare to a reference that we generated by the same block creation functions but using a different storage (like in-memory) and then we know the expected state? But that doesn't test the LMDB layout.

 The issue says: "bit-compares it against a reference". So we need a reference LMDB file that is known to be correct.

 How about we generate the reference LMDB file by running a known good version of the code? But we don't have one.

 Alternatively, we can design the test chain to be very simple and then hand-craft the expected LMDB layout? That is error-prone and not scalable.

 Given the complexity, I think the intended approach is:

   Step 1: Create a test chain (using the existing Tari test helpers) and save the blocks to a JSON file (for reproducibility).
   Step 2: Use the JSON file to create a reference LMDB file by writing the chain using the LMDB database (the code under test) and then save that LMDB file as the reference (committed to the repo).
   Step 3: In the write test, we read the JSON file, create a new LMDB, write the chain, and then compare the new LMDB file to the reference LMDB file (byte-by-byte).
   Step 4: In the read test, we open the reference LMDB file and then verify that we can read all the data correctly.

 However, note: the write test is then testing that the LMDB writing is consistent over time (if the reference was generated by an older version). But if we change the LMDB writing code, the write test will fail and we will have to update the reference.

 This is acceptable for a unit test that is meant to catch regressions.

 But note: the issue says "Create a reproducible test chain", meaning we are to generate the chain in the test? And then we are to create the reference LMDB from that chain? Then we don't need to commit the reference? We can generate the reference in the test setup and then use it for the write test? But then the write test is comparing two LMDBs generated by the same code? That doesn't test anything.

 Let me re-read: "A write test creates a new LMDB file from the JSON data and bit-compares it against a reference"

 So we have:
   - JSON data: the test chain data (blocks, etc.) in JSON format.
   - Reference LMDB: a precomputed LMDB file that is known to be correct.

 How do we get the reference LMDB? We generate it once from the JSON data using the LMDB code (or a trusted method) and then commit it.

 Since we are to write the unit tests, we will:
   - Create the JSON file (by generating the test chain and serializing to JSON) and commit it.
   - Generate the reference LMDB from the JSON file (using the LMDB code) and commit it.

 Then in the test:
   - Write test: read the JSON, create a new LMDB, write the chain, and compare the new LMDB file to the reference LMDB file.
   - Read test: open the reference LMDB and verify the data.

 However, note: the issue says "All block data is saved in a JSON file for reproducibility". So we are saving the chain data in JSON.

 Steps for the test:

   1. We will create a test module that:
        - Generates the test chain (genesis, 10 main-chain, 10-block fork from block 5) and saves it to a JSON file (in the test resources directory).
        - Then, we use the LMDB database to write that chain to an LMDB file (the reference) and save it (also in test resources).

   2. But note: we don't want to run the generation every time in the test? Because it might be slow and we want the reference to be fixed.

   3. We will generate the JSON and the reference LMDB once and commit them to the repo.

   4. Then, in the unit tests, we:
        - For the write test: read the JSON, create a temporary LMDB, write the chain from the JSON, and then compare the temporary LMDB file to the reference LMDB file (on disk).
        - For the read test: open the reference LMDB file and then verify that we can read all the expected data.

 Implementation:

   We will create:
        - `test_chain.json`: in `base_layer/core/src/chain_storage/lmdb_db/test_resources/`
        - `reference.lmdb`: in the same directory.

   However, note: the LMDB file is actually a directory (because LMDB uses a directory for the environment and then creates data.mdb and lock.mdb). So we cannot just have a single file.

   We will have to store the entire LMDB environment directory as the reference.

   Alternatively, we can store the LMDB data file (data.mdb) and ignore the lock file? But note: the lock file is created by the LMDB environment and we don't want to include it in the reference because it is transient.

   We can do: the reference is the data.mdb file? But note: the LMDB environment also has a lock file and we are not supposed to share the lock file.

   Actually, when we open an LMDB environment in read-only mode, we don't need the lock file? But the data.mdb is the main file.

   However, the issue says "bit-compares it against a reference", meaning we are comparing the entire LMDB environment? But the lock file is not part of the data.

   We can decide to only compare the data.mdb file? Because the lock file is created by the LMDB library and we don't care about it.

   Steps for the write test:
        - Create a temporary directory for the new LMDB environment.
        - Open the LMDB database in that directory (in write mode).
        - Write the chain (from the JSON) to the database.
        - Close the database.
        - Then, compare the data.mdb file in the temporary directory to the reference data.mdb file (from the committed reference).

   But note: the LMDB data file might have some free space or padding that is not deterministic? We want a bit-exact match.

   We can control the LMDB environment settings to make it deterministic? For example, by setting the map size and not allowing growth? And by writing in the same order.

   Alternatively, we can use the same LMDB environment settings for both the reference and the test.

   We will set:
        - Map size: fixed (say, 100 MB)
        - No subdir (if we are using a single file? Actually, LMDB by default uses a directory and creates data.mdb and lock.mdb. We can set the environment to use a single file? Not exactly, but we can specify the path for the data file? Actually, the data.mdb is always in the environment directory.

   We can set the environment to be created with:
        let env = LMDBBuilder::new()
            .set_map_size(10_000_000)
            .set_path(path)
            .build()?;

   Then, when we write, we write the same data in the same order, so the data.mdb should be identical.

   However, note: the LMDB library might use different free space strategies? We are writing the same data in the same order, so the layout should be the same.

   We will assume that.

   Steps for generating the reference (to be done once and committed):

        - Create a temporary directory.
        - Create an LMDB environment in that directory with fixed settings.
        - Write the test chain (from the JSON) to the LMDB.
        - Close the environment.
        - Copy the data.mdb file to the test resources as the reference.

   Then, in the write test, we do the same and compare the data.mdb.

   For the read test, we open the reference LMDB environment (in read-only mode) from the committed data.mdb file (and we have to set the environment to use the directory containing the reference data.mdb?).

   Actually, we will store the reference as a directory containing only the data.mdb file? But note: the LMDB environment expects a directory that may contain lock.mdb. We don't want to commit the lock.mdb.

   We can do: the reference is stored as a directory that contains the data.mdb file. When we open the environment for reading, we point to that directory and set the environment to be read-only. The LMDB library will create a lock.mdb in that directory? But we don't want to modify the reference.

   We can open the environment in read-only mode and set the `set_max_readers` to 1 and `set_readonly(true)`. Then, the LMDB library will not create a lock file? Actually, it will still try to create a lock file. We can set the environment to be on a read-only filesystem? Or we can copy the reference to a temporary directory for the read test? But that would be inefficient.

   Alternatively, we can store the reference as a single file (the data.mdb) and then when we open the environment, we set the path to the directory containing that file and then set the environment to be read-only. We accept that a lock file will be created in the reference directory? But we don't want to modify the committed reference.

   Therefore, we will copy the reference data.mdb to a temporary directory for the read test? Then we don't pollute the committed reference.

   However, the issue does not specify the exact method. We'll do:

        For the write test:
            - We create a temporary directory for the new LMDB.
            - We write the chain to that LMDB (using the same settings as the reference).
            - We compare the data.mdb file in the temporary directory to the reference data.mdb file (which is in the test resources).

        For the read test:
            - We create a temporary directory and copy the reference data.mdb file to it.
            - We open the LMDB environment in that temporary directory (in read-only mode).
            - Then we perform the read verifications.

   This way, we don't modify the committed reference.

   Now, let's outline the code:

   We will create a new test file: `base_layer/core/src/chain_storage/lmdb_db/lmdb_tests.rs`

   We will use the following modules:

        use tari_core::chain_storage::lmdb_db::{LMDBDatabase, LMDBBuilder};
        use tari_core::transactions::tari_amount::MicroTari;
        use tari_core::blocks::{Block, BlockHeader};
        use tari_core::consensus::ConsensusConstants;
        use tari_core::chain_storage::BlockchainDatabase;
        use tari_test_utils::unpack_enum;
        use std::path::PathBuf;
        use std::fs;
        use std::fs::File;
        use std::io::Write;
        use serde::{Deserialize, Serialize};
        use serde_json;

   But note: we are in the base_layer, so we can use the existing test helpers.

   However, to avoid too many dependencies, we will create the test chain using the same methods as in the existing blockchain tests.

   We note that there is a `create_genesis_block` function in the test helpers.

   We will create a helper function to generate the test chain and return:
        - The genesis block
        - The vector of main chain blocks (height 1 to 10)
        - The vector of fork blocks (height 6 to 15, branching from height 5)

   Then, we will serialize the entire chain (genesis, main chain, fork) to JSON.

   We will define a struct for the JSON serialization that contains:
        - genesis: Block
        - main_chain: Vec<Block>
        - fork_chain: Vec<Block>

   But note: the fork chain is 10 blocks from block 5, so the fork chain starts at height 6 and goes to height 15.

   Steps for generating the chain:

        let mut rng = OsRng::new().unwrap();
        let consensus_constants = ConsensusConstants::default();
        let genesis = create_genesis_block(&mut rng, &consensus_constants);
        let mut main_chain = Vec::new();
        let mut prev = genesis.clone();
        for i in 1..=10 {
            let block = create_block(&mut rng, &consensus_constants, &prev, vec![]);
            main_chain.push(block);
            prev = main_chain.last().unwrap().clone();
        }
        // Now, fork from block at height 5 (which is main_chain[4] because 0-indexed: genesis=0, then 1..10 -> indices 0..9 for main_chain[0] is height1, so height5 is main_chain[4])
        let mut fork_chain = Vec::new();
        let mut prev_fork = main_chain[4].clone(); // height 5
        for i in 6..=15 {
            let block = create_block(&mut rng, &consensus_constants, &prev_fork, vec![]);
            fork_chain.push(block);
            prev_fork = fork_chain.last().unwrap().clone();
        }

   Then, we serialize:
        let test_chain = TestChain {
            genesis,
            main_chain,
            fork_chain,
        };
        let json = serde_json::to_string_pretty(&test_chain).unwrap();

   And write to a file.

   For the reference LMDB, we will create a function that, given the test chain, writes it to an LMDB environment and returns the path to the data.mdb file? But we want to save the data.mdb file.

   We will create a temporary directory, write the chain to the LMDB in that directory, and then copy the data.mdb file to the test resources.

   However, note: we are going to commit the reference data.mdb and the JSON file.

   We will not include the generation code in the test? We will run it once to generate the reference and then check in the files.

   But to make the test self-contained, we can generate the reference in the test setup if it doesn't exist? But then we