[package]
name = "tari_common_sqlite"
description = "Tari cryptocurrency wallet library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
bundled = ["libsqlite3-sys/bundled"]

[dependencies]
tari_utilities = { workspace = true }

diesel = { version = "2.3.8", features = [
    "sqlite",
    "r2d2",
    "serde_json",
    "chrono",
    "64-column-tables",
] }
diesel_migrations = "2.3"
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "rt"] }
lazy_static = "1.5.0"
libsqlite3-sys = { version = "0.30.1", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["sync", "macros", "rt", "time", "rt-multi-thread"] }

[package.metadata.cargo-machete]
ignored = ["libsqlite3-sys"]
