[package]
name = "minotari_wallet_grpc_client"
description = "Base node GRPC client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage = "https://tari.com"
readme = "README.md"
license.workspace = true

[dependencies]
minotari_app_grpc = { path = "../../../applications/minotari_app_grpc" }
tari_common_types = { path = "../../../base_layer/common_types" }
tari_common = { path = "../../../common" }

thiserror = "1.0.35"
tonic = { version = "0.13.1", default-features = false, features = ["codegen", "transport", "tls-ring"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
