[package]
name = "minotari_node_grpc_client"
description = "Base node GRPC client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage = "https://tari.com"
readme = "README.md"
license.workspace = true

[dependencies]
minotari_app_grpc = { workspace = true }

#tonic = { version = "0.13.1", default-features = false, features = ["codegen", "transport", "prost"] }
#prost = "0.11.0"
#prost-types = "0.11.1"
#thiserror = "1.0.35"
#url = "2.3"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }

#[build-dependencies]
#tonic-build = "0.13.1"
