alter table outbound_transactions add unique_id blob;
alter table completed_transactions add unique_id blob;
alter table outputs add unique_id blob;
alter table outputs add metadata blob;
alter table outputs add features_asset_public_key blob;
alter table outputs add features_mint_asset_public_key blob;
alter table outputs add features_mint_asset_owner_commitment blob;
alter table outputs add parent_public_key blob;
alter table inbound_transactions add unique_id blob;
