//  Copyright 2020, The Tari Project
//
//  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
//  following conditions are met:
//
//  1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
//  disclaimer.
//
//  2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
//  following disclaimer in the documentation and/or other materials provided with the distribution.
//
//  3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
//  products derived from this software without specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
//  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
//  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
//  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

pub(crate) mod inner;
mod monerod_method;
pub(crate) mod service;
pub(crate) mod static_responses;
pub(crate) mod utils;

#[cfg(test)]
mod test {
    use std::{str::FromStr, time::Instant};

    use anyhow::{anyhow, Error};
    use chrono::{Local, Timelike};
    use monero::{blockdata::transaction::SubField::MergeMining, Hash, VarInt};
    use reqwest::Client;
    use serde_json::json;
    use tari_core::proof_of_work::monero_rx;

    use crate::proxy::{
        monerod_method::MonerodMethod,
        static_responses::{get_empty_monero_block, BLOCK_HASH_AT_3336491, BLOCK_HEIGHT_3336491, TIMESTAMP_AT_3336491},
        utils::convert_reqwest_response_to_hyper_json_response,
    };

    /// This is the public Monero primary donation address for their general fund
    /// (See https://www.getmonero.org/get-started/contributing/)
    const DEFAULT_MONERO_ADDRESS: &str =
        "44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A";

    async fn get_json_rpc(
        method: MonerodMethod,
        json_rpc_port: u16,
        hyper_json_response: bool,
        hash: Option<String>,
        block_blob: Option<String>,
    ) -> Result<String, Error> {
        match method {
            MonerodMethod::GetHeight => get_response(json_rpc_port, method).await,
            MonerodMethod::GetBlockTemplate |
            MonerodMethod::GetVersion |
            MonerodMethod::SubmitBlock |
            MonerodMethod::GetBlockHeaderByHash |
            MonerodMethod::GetLastBlockHeader |
            MonerodMethod::GetBlock => {
                json_rpc_request_body(method, json_rpc_port, hyper_json_response, hash, block_blob).await
            },
            _ => Err(anyhow!("'{}' not supported", method)),
        }
    }

    async fn get_response(json_rpc_port: u16, method: MonerodMethod) -> Result<String, Error> {
        let full_address = format!("http://127.0.0.1:{}", json_rpc_port);
        match reqwest::get(format!("{}/{}", full_address, method))
            .await
            .unwrap()
            .json::<serde_json::Value>()
            .await
        {
            Ok(val) => {
                println!("{}: {}", method, val);
                Ok(val.to_string())
            },
            Err(e) => Err(e.into()),
        }
    }

    // The static XMRig request bodies in this test helper function are for testing purposes only. Their content can be
    // verified for similarity with the actual request bodies that are generated by XMRig as the first log entry in
    // `applications/minotari_merge_mining_proxy/src/proxy/inner.rs` method `pub(crate) async fn handle(`.
    async fn json_rpc_request_body(
        method: MonerodMethod,
        json_rpc_port: u16,
        hyper_json_response: bool,
        hash: Option<String>,
        block_blob: Option<String>,
    ) -> Result<String, Error> {
        let rpc_method = format!("{}", method);
        let request_body = match method {
            MonerodMethod::GetBlockTemplate => json!({
                "jsonrpc": "2.0",
                "id": "0",
                "method": rpc_method,
                "params": {
                    "wallet_address": DEFAULT_MONERO_ADDRESS,
                }
            }),
            MonerodMethod::GetVersion | MonerodMethod::GetLastBlockHeader => json!({
                "jsonrpc": "2.0",
                "id": "0",
                "method": rpc_method,
                "params": {}
            }),
            MonerodMethod::SubmitBlock => {
                let block_blob = if let Some(blob) = block_blob {
                    blob
                } else {
                    const ARBITRARY_MERGE_MINING_HASH: &str =
                        "8e6dab82d22909b40bda27ec0e96aa0c6c0012023d353f3be941eb6ef1793cad";
                    let merge_mining_tag = Some(MergeMining(
                        VarInt(0),
                        Hash::from_str(ARBITRARY_MERGE_MINING_HASH).expect("will not fail"),
                    ));
                    let block = get_empty_monero_block(
                        Hash::from_str(BLOCK_HASH_AT_3336491)?,
                        TIMESTAMP_AT_3336491,
                        BLOCK_HEIGHT_3336491,
                        merge_mining_tag,
                    );
                    monero_rx::serialize_monero_block_to_hex(&block)?
                };
                assert!(monero_rx::deserialize_monero_block_from_hex(&block_blob).is_ok());

                json!({
                    "jsonrpc": "2.0",
                    "id": "0",
                    "method": rpc_method,
                    // These request params were generated by XMRig when submitting a block that was solved during merge
                    // mining on esmeralda.
                    "params": [block_blob]
                })
            },
            MonerodMethod::GetBlockHeaderByHash | MonerodMethod::GetBlock => json!({
                "jsonrpc": "2.0",
                "id": "0",
                "method": rpc_method,
                "params": {
                    "hash": hash.unwrap_or(BLOCK_HASH_AT_3336491.to_string()),
                }
            }),
            _ => return Err(anyhow!("'{}' not supported", method)),
        };
        let rpc_url = format!("http://127.0.0.1:{}/json_rpc", json_rpc_port);

        // Create an HTTP client
        let client = Client::new();

        // Send the POST request
        let response = client.post(rpc_url).json(&request_body).send().await?;

        // Parse the response body
        if response.status().is_success() {
            if hyper_json_response {
                let hyper_json_response = convert_reqwest_response_to_hyper_json_response(response).await?;

                println!();
                println!("{} - response:   {:?}", method, hyper_json_response);
                println!("{} - status:     {:?}", method, hyper_json_response.status());
                println!("{} - version:    {:?}", method, hyper_json_response.version());
                println!("{} - headers:    {:?}", method, hyper_json_response.headers());
                println!("{} - extensions: {:?}", method, hyper_json_response.extensions());
                println!("{} - body:       {:?}", method, hyper_json_response.body());

                let response_json = hyper_json_response.body();
                if response_json.get("error").is_some() {
                    return Err(anyhow!("'{}' failed ({})", method, response_json));
                }
                if response_json.get("result").is_none() {
                    return Err(anyhow!("'{}' failed ({})", method, response_json));
                }

                Ok(response_json.to_string())
            } else {
                let response_text = response.text().await?;
                let response_json: serde_json::Value = serde_json::from_str(&response_text)?;
                if response_json.get("error").is_some() {
                    return Err(anyhow!("'{}' failed ({})", method, response_text));
                }
                if response_json.get("result").is_none() {
                    return Err(anyhow!("'{}' failed ({})", method, response_text));
                }
                Ok(response_text)
            }
        } else {
            Err(anyhow!("{} failed({})", method, response.status()))
        }
    }

    fn time_now() -> String {
        let now = Local::now();
        format!(
            "{:02}:{:02}:{:02}.{:03}",
            now.hour(),
            now.minute(),
            now.second(),
            now.timestamp_subsec_millis()
        )
    }

    pub(crate) async fn inner_json_rpc(
        method: MonerodMethod,
        json_rpc_port: u16,
        responses: &mut Vec<String>,
        count: usize,
        hyper_json_response: bool,
        hash: Option<String>,
        block_blob: Option<String>,
    ) {
        let start = Instant::now();
        let response = get_json_rpc(method, json_rpc_port, hyper_json_response, hash, block_blob).await;
        match response {
            Ok(val) => {
                responses.push(format!(
                    "  {}: method: {}; time now: {}; duration: {:.2?}, response length: {}, response body: {}",
                    count,
                    method,
                    time_now(),
                    start.elapsed(),
                    val.len(),
                    val
                ));
            },
            Err(err) => {
                responses.push(format!(
                    "  {}: method: {}; time now: {}; duration: {:.2?}, response length: {}, Error: {}",
                    count,
                    method,
                    time_now(),
                    start.elapsed(),
                    err.to_string().len(),
                    err
                ));
            },
        }
    }

    // To execute this test a merge mining proxy must be running (just verify the port, default used), ideally when
    // RandomX mining with XMRig is taking place.
    #[tokio::test]
    #[ignore]
    async fn test_get_monerod_info() {
        let json_rpc_port = 18081;
        let tick = tokio::time::Duration::from_secs(2);
        let mut interval = tokio::time::interval(tick);
        let mut responses = Vec::with_capacity(50);
        for method in [
            MonerodMethod::GetHeight,
            MonerodMethod::GetVersion,
            MonerodMethod::GetBlockTemplate,
            MonerodMethod::SubmitBlock,
            MonerodMethod::GetBlockHeaderByHash,
            MonerodMethod::GetLastBlockHeader,
        ] {
            let mut count = 0;
            responses.push(format!("method: {}, tick: {:.2?}", method, tick));
            loop {
                interval.tick().await;
                count += 1;
                inner_json_rpc(method, json_rpc_port, &mut responses, count, false, None, None).await;
                if count >= 2 {
                    break;
                }
            }
        }
        for response in responses {
            println!("{}", response);
        }
    }

    // To execute this test a merge mining proxy must be running (just verify the port, default used), ideally when
    // RandomX mining with XMRig is taking place.
    #[tokio::test]
    #[ignore]
    async fn stress_test_get_monerod_info() {
        let json_rpc_port = 18081;
        let tick = tokio::time::Duration::from_millis(1000);
        let mut interval = tokio::time::interval(tick);
        let mut responses = Vec::with_capacity(3010);
        for method in [
            MonerodMethod::GetHeight,
            MonerodMethod::GetVersion,
            MonerodMethod::GetBlockTemplate,
            MonerodMethod::SubmitBlock,
            MonerodMethod::GetBlockHeaderByHash,
            MonerodMethod::GetLastBlockHeader,
        ] {
            let mut count = 0;
            responses.push(format!("method: {}, tick: {:.2?}", method, tick));
            loop {
                interval.tick().await;
                count += 1;
                inner_json_rpc(method, json_rpc_port, &mut responses, count, false, None, None).await;
                if count >= 500 {
                    break;
                }
            }
        }
        for response in responses {
            println!("{}", response);
        }
    }
}
