[package]
name = "tari_jellyfish"
description = "A collection of utilities for working with the Jellyfish Merkle Tree"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_hashing = { workspace = true }
tari_crypto = { workspace = true }

serde = { workspace = true, features = ["derive"] }
borsh = { workspace = true }
digest = "0.10"
thiserror = { workspace = true }
indexmap = { version = "2.6", features = ["serde"] }