[package]
name = "minotari_ledger_wallet_common"
description = "Common utilities and types for the Minotari Ledger Wallet application"
version.workspace = true
edition.workspace = true
#Note: `rust-version` is not specified here as this msut be kept in sync with the ledger-app-builder
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
borsh = { workspace = true, features = ["derive"] }
bs58 = { version = "0.5.1", default-features = false, features = ["alloc"] }
serde = { version = "1",  default-features = false, features = ["derive"] }
