cargo publish --package tari_storage --dry-run
cargo publish --package tari_shutdown --dry-run
cargo publish --package tari_metrics --dry-run
cargo publish --package tari_max_size --dry-run
cargo publish --package tari_script --dry-run
cargo publish --package tari_hashing --dry-run
cargo publish --package tari_jellyfish --dry-run
cargo publish --package tari_comms_rpc_macros --dry-run
cargo publish --package tari_common_sqlite --dry-run
cargo publish --package tari_features --dry-run
cargo publish --package tari_test_utils --dry-run
cargo publish --package tari_common --dry-run
cargo publish --package tari_comms --dry-run
cargo publish --package tari_comms_dht --dry-run
cargo publish --package minotari_ledger_wallet_common --dry-run
cargo publish --package tari_common_types --dry-run
cargo publish --package tari_sidechain --dry-run
cargo publish --package minotari_ledger_wallet_comms --dry-run
cargo publish --package tari_service_framework --dry-run
cargo publish --package tari_transaction_components --dry-run
cargo publish --package tari_transaction_key_manager --dry-run
cargo publish --package tari_node_components --dry-run
cargo publish --package tari_p2p --dry-run
cargo publish --package tari_libtor --dry-run
cargo publish --package tari_mmr --dry-run
cargo publish --package tari_core --dry-run
cargo publish --package minotari_node_wallet_client --dry-run
cargo publish --package minotari_wallet --dry-run
cargo publish --package minotari_app_grpc --dry-run
cargo publish --package minotari_app_utilities --dry-run
cargo publish --package minotari_wallet_grpc_client --dry-run
cargo publish --package minotari_node_grpc_client --dry-run