ALTER TABLE outputs RENAME TO outputs_old;
CREATE TABLE outputs (
    id                         INTEGER PRIMARY KEY NOT NULL,
    commitment                 BLOB                NULL,
    spending_key               TEXT                NOT NULL,
    value                      BIGINT              NOT NULL,
    output_type                INTEGER             NOT NULL,
    maturity                   BIGINT              NOT NULL,
    status                     INTEGER             NOT NULL,
    hash                       BLOB                NULL,
    script                     BLOB                NOT NULL,
    input_data                 BLOB                NOT NULL,
    script_private_key         TEXT                NOT NULL,
    script_lock_height         UNSIGNED BIGINT     NOT NULL DEFAULT 0,
    sender_offset_public_key   BLOB                NOT NULL,
    metadata_signature_ephemeral_commitment   BLOB                NOT NULL,
    metadata_signature_ephemeral_pubkey   BLOB                NOT NULL,
    metadata_signature_u_a     BLOB                NOT NULL,
    metadata_signature_u_x     BLOB                NOT NULL,
    metadata_signature_u_y     BLOB                NOT NULL,
    mined_height               UNSIGNED BIGINT     NULL,
    mined_in_block             BLOB                NULL,
    mined_mmr_position         BIGINT              NULL,
    marked_deleted_at_height   BIGINT              NULL,
    marked_deleted_in_block    BLOB                NULL,
    received_in_tx_id          BIGINT              NULL,
    spent_in_tx_id             BIGINT              NULL,
    coinbase_block_height      UNSIGNED BIGINT     NULL,
    metadata                   BLOB                NULL,
    features_json              TEXT                NOT NULL DEFAULT '{}',
    spending_priority          UNSIGNED INTEGER    NOT NULL DEFAULT 500,
    covenant                   BLOB                NOT NULL,
    mined_timestamp            DATETIME            NULL,
    encrypted_value            BLOB                NOT NULL,
    minimum_value_promise    BIGINT              NOT NULL,
    source                     INTEGER             NOT NULL DEFAULT 0,
    CONSTRAINT unique_commitment UNIQUE (commitment)
);