[package]
name = "minotari_node_wallet_client"
description = "A client for the Minotari Node gRPC service, used by the Minotari Console Wallet application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_transaction_components = { workspace = true}
tari_utilities = { workspace = true }
tari_shutdown = { workspace = true }
anyhow = { workspace = true }
url = { version = "2.5.4", features = ["default", "serde"] }
reqwest = { version = "0.12", features = ["default", "json"] }
async-trait = "0.1.88"
tokio = { workspace = true, features = ["sync"] }
log = { workspace = true, features = [] }
serde_json = { workspace = true }
serde = { workspace = true }
