# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/transactions/key_manager/schema.rs"

[migrations_directory]
dir = "src/transactions/key_manager/migrations"
