[package]
name = "minotari_offline_signer"
description = "Offline transaction signing tool for Tari"
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "minotari_offline_signer"
path = "src/main.rs"

[dependencies]
tari_common = { workspace = true }
tari_common_types = { workspace = true }
tari_transaction_components = { workspace = true }
tari_utilities = { workspace = true }

clap = { version = "^4.0", features = ["derive", "env"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
keyring = { version = "^3", features = ["apple-native", "windows-native", "sync-secret-service"] }
chacha20poly1305 = "^0.10"
argon2 = { version = "0.6.0-rc.8", features = ["password-hash"] }
phc = { version = "0.6.1"}
rand = { workspace = true }
zeroize = "^1"

