// Copyright 2023. The Tari Project
// SPDX-License-Identifier: BSD-3-Clause

// This file was generated by cargo-bindgen. Please do not edit manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Configuration for a comms node
 */
struct P2pConfig;

/**
 * Peer seed configuration
 */
struct PeerSeedsConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * None
 */
void create_chat_client(struct P2pConfig *config,
                        const char *identity_file_path,
                        struct PeerSeedsConfig *peer_seeds_config,
                        const char *network_str);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
